### ISSUE TITLE
Reporter not picking up tipped feeds from autopay

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#362]
One of our testers is creating funded feeds on the `Autopay` contract, and the tip listener component of the telliot reporter is not finding those and reporting to them for some reason..

**Comment by akremstudy** [comment]
@oraclown which chain is this on?

**Comment by oraclown** [comment]
not sure, @spuddyminer ?

**Comment by spuddyminer** [comment]
I've tested these features on mumbai only, so probably mumbai?

Some thoughts on the tip listener functionality:
I think when this problem was first discussed, I was missing some understanding of how it's intended to work.

- If it is assumed that the person setting up the feed is the same person reporting for the feed? If so, then it works perfectly.
-  Do we want it to work in a way that anybody running telliot can compete for all tips automatically? If so, then telliot needs to be able to automatically build feeds from the autopay tip transactions / feed creation.

Anyway, I'm saying things that we already know. Hope I can help more lmk 🤙

**Comment by oraclown** [comment]
> I've tested these features on mumbai only, so probably mumbai?
> 
> Some thoughts on the tip listener functionality: I think when this problem was first discussed, I was missing some understanding of how it's intended to work.
> 
> * If it is assumed that the person setting up the feed is the same person reporting for the feed? If so, then it works perfectly.
> * Do we want it to work in a way that anybody running telliot can compete for all tips automatically? If so, then telliot needs to be able to automatically build feeds from the autopay tip transactions / feed creation.
> 
> Anyway, I'm saying things that we already know. Hope I can help more lmk 🤙

Yes, we want all your reporters to report for any feeds / one-time tips created on testnet, so new users don't have to worry about reporting. To do that, we need the query data in autopay somehow, and some getters for.. getting that info to reconstruct the query type on the telliot end. @akremstudy and @tkernell added that functionality to autopay, I think. And looks like @brendaloya deployed those contracts on rinkeby, and I'm assuming we'll do the same for other chains like Mumbai soon

**Comment by oraclown** [comment]
Closing bc current reporters will report for feeds created on Autopay (not 360 Autopay w/ query data contract) that we have query ids for in the query_catalog.
