### ISSUE TITLE
Reporter lock check broken

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#426]
User has 3000 TRB staked, but it says they're in reporter lock. They should be able to report more frequently.
```
3000 TRB staked and says im in reporter lock. Im not sure if i missed something historically that mention we can only report once every so often, but isnt having a time restriction on the reporter address conflicting with the point of making a single reporter wallet? If I am going to get time restricted I might aswell have kept the 30 reporter addresses I had to allow fast rotation of reporter wallets, especially if there are tips to be contested for. 
```

**Comment by akremstudy** [comment]
I don't think this is broken because if you have 3000 stakes by a single address you are still allowed 30 reports in a 12 hour period.  The difference between using one staker and multiple stakers would be the one staker has to wait  24 minutes between reports where as the 30 stakers if they report all at once have to wait 12 hours.  I guess one caveat of using 30 stakers instead of one is having the flexibility of controlling the time they report where as the one staker is affixed to the 24 minute wait period. I got 24 minutes by this calculation (43200 / (3000/100) = 1440) , assuming the stake amount is 100 cause the stake amount could possibly change.  @tkernell @oraclown sound right to y'all?

**Comment by LP-Crypto-Scholar** [comment]
I don't see why we need that calculation at all. Like if I want to report at 30 reporters in a 6 hour period there shouldn't be an limitation on this. The report contract API could pull the latest 12 hours worth of transactions for the staked address and if amount_staked / 100 > float(response from api) then report is in lock.

**Comment by akremstudy** [comment]
> Like if I want to report with 30 reporters in a 6 hour period there shouldn't be an limitation on this.

not sure what you mean, but there is no limitation for 30 reporters to report in a 6hr window.  The 30 reporters can report all at the same time and that shouldn't be an issue.  The limitation is for a single reporter with a single stake.  The transaction will revert for a second report thats executed in less than 12 hours by the same reporter.

**Comment by akremstudy** [comment]
So if one of the 30 reporters tries to report more than once in a 12hr window then the transaction will revert.  Telliot is checking for that to avoid the loss of gas.  Sorry if I'm not making sense.

**Comment by LP-Crypto-Scholar** [comment]
Yeah okay. But isnt there a current limitiation due to the below line which results in my telliot module being locked for 24 minutes? 
line 186        reporter_lock = 43200 / math.floor(self.staker_info.stake_balance / self.stake_amount)

BTW im only running a single instance of the telliot module. So the 30 reporters can still report if I run mutliple instances however im only running 1 instance currently. Hopefully this makes sense

**Comment by LP-Crypto-Scholar** [comment]
Also, the equation allows for other competitors to know exactly how often you'll submit thus allowing them the opportunity to front run. This code needs to be dynamic. I cannot report every 24 minutes or else someone will report every 24 minutes 3 seconds before I do. I'm using myself as a case study but this can happen to anyone. Considering there are only 3 reporters on the network currently, it's going to be very easy to see patterns.

**Comment by LP-Crypto-Scholar** [comment]
Following on from the above, I changed the 43200 value to 40 so that i would essentially be able to report whenever i felt like it (regardless of the profit %) and I got reverted. It concludes that even though I have 30 stakes available to report every 12 hours, I need to wait 24 minutes between reports. Im assuming Krasi or the other compitor has already picked up on this as Im getting front run already even while uses flashbots as they know ill report evey 24 minutes if the profit is postive.
![image](https://user-images.githubusercontent.com/95621713/200117669-4f21a7d4-0cc2-4355-9175-b491cbc0c584.png)

**Comment by akremstudy** [comment]
@LP-Crypto-Scholar the "limitation" in the script is there to protect the user from wasting gas.  The actual limitation is in the oracle contract which has a limitation of a 12 hour period wait, for a single stake, after reporting to allow time for a dispute.  If you are running a single instance vs 30 instances thats totally up to you.  But you are right it could give a competitor some what of an advantage after seeing your report to know when you will be able to report again but that goes both ways because you can also see their single reporter's report and see that they can't report again for 12 hours. Also, after your first report you can decide not to report at the 24 minute period (ie 1 reporter/30stakes) and it all boils down what strategy you employ I guess.

**Comment by oraclown** [comment]
@akremstudy is right.

Also, our goal is to make telliot a reference implementation of client software for interacting with Tellor. Providing a competitive (profit) reporter is not our goal and doesn't make sense since it's open-source.
