### ISSUE TITLE
tries to report for one-time tips when tips haven't been claimed

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#459]
@spuddyminer can you add more details on how to reproduce?

**Comment by spuddyminer** [comment]
Expected behavior: Telliot instances (that are expecting profit) listen and submit for Autopay tips that are "new" (having no qualifying submission) ignoring any tips that are waiting 12 hours to be claimed.

Observed behavior: Telliot instances that are expecting profit may continue to submit for tips that can be claimed by a prior submission. (which is a waste of gas, as only the first qualifying submission is eligible to receive the tip.)

**Comment by akremstudy** [comment]
@spuddyminer I added a test that shows one time tips aren't suggested if they've already been reported for. I'm wondering if this could be something else. Can you share the transactions if this is happening still or if it happens again, please.
