### ISSUE TITLE
Use submodules for Tellor contracts used in tests

### ISSUE THREAD

**Issue by oraclown** [tellor-io/telliot-feeds#678]
Currently, Tellor contracts used in tests (`Autopay`, `TellorFlex`, `Governance`, etc.) are just copied over to this repository from other Tellor repos. Instead, maybe it's possible to use git submodules like [here](https://github.com/tellor-io/tellor-parachain-demo), so it's easier to ensure this repo updates with any changes to the original contracts repositories.

**Comment by akremstudy** [comment]
I think this would be nice, but I wonder if this would cause existing tests to fail due to the changes in the contracts (maybe this is a good thing idk).

**Comment by oraclown** [comment]
> I think this would be nice, but I wonder if this would cause existing tests to fail due to the changes in the contracts (maybe this is a good thing idk).

Might be a good thing, as it'd force us to keep up w/ contract changes.

**Comment by oraclown** [comment]
And you can set the commit hash for the submodule, so they wouldn't break automatically. Just when you update the submodule.

**Comment by akremstudy** [comment]
Using submodules adds all the contents in that repo so that would add 4 or 5 repos and all their contents. Also another issue is when compiling those contracts you run into dependency issues or import errors.  I think the way it is now is the most efficient. Also tried to add contracts as dependencies in brownie config file but just ran into import errors and couldn't resolve.
